export const lang = [
    {
        base: {
            file: 'Image file',
            link: 'Image link',
            name: 'Name',
            width: 'Width',
            height: 'Height',
            fit: 'Fit',
            rotate: 'Rotate',
            scale: 'Scale',
            mode: 'Mode',
            process: 'Process',
            result: 'Result',
            code: 'Code',
            copy: 'Copy',
            header: '.h',
            bin: 'bin',
            bulk: 'Bulk encode',
            send: 'Send',
            info: 'Info',
            bulk_info: 'Select multiple files first',
        },
        filters: {
            display: 'Display style',
            grid: 'Grid',
            invert_b: 'Invert background',
            preview: 'Preview',
            invert: 'Invert',
            brightness: 'Brightness',
            contrast: 'Contrast',
            saturate: 'Saturate',
            blur: 'Blur',
            edges: 'Edges',
            sobel: 'Sobel edges',
            dither: 'Dithering',
            threshold: 'Threshold',
            median: 'Median edges',
            editor: 'Editor',
            png: 'Save .png',
            reset: 'Reset',
        },
        display: ['Screen', 'Paper']
    },
    {
        base: {
            file: 'Файл',
            link: 'Ссылка',
            name: 'Имя',
            width: 'Ширина',
            height: 'Высота',
            fit: 'Центрировать',
            rotate: 'Повернуть',
            scale: 'Масштаб',
            mode: 'Режим',
            process: 'Процесс',
            result: 'Результат',
            code: 'Код',
            copy: 'Копировать',
            header: '.h',
            bin: 'bin',
            bulk: 'Массовая конвертация',
            send: 'Отправить',
            info: 'Инфо',
            bulk_info: 'Сначала выбери несколько файлов',
        },
        filters: {
            display: 'Стиль отображения',
            grid: 'Сетка',
            invert_b: 'Инвертировать фон',
            preview: 'Предпросмотр',
            invert: 'Инвертировать',
            brightness: 'Яркость',
            contrast: 'Контраст',
            saturate: 'Насыщенность',
            blur: 'Размытие',
            edges: 'Усилить края',
            sobel: 'Выделить края',
            dither: 'Dithering',
            threshold: 'Порог',
            median: 'Выделить край',
            editor: 'Редактор',
            png: 'Сохранить .png',
            reset: 'Сброс',
        },
        display: ['Дисплей', 'Бумага']
    }
];